version: "3.8"
services:
  lb:
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports: 
      - 9090:9090
    container_name: oneeaterieslb
    depends_on: 
      - api_service
  api_service:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - 8080
    environment: 
      - spring_data_mongodb_host=mongo_db
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017